name: deploy-develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    branches:
      - develop
jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          cd app
          pip install -r requirements.txt -t ./
          zip -r package.zip ./*
          pip3 install awscli
          aws lambda update-function-code --function-name ll-now-generate-image-HelloWorldFunction-AwoHFtV5bM8l --zip-file fileb://package.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1